name: Check Links
on:
  push:
    branches:
      - main 
jobs:
  run-script:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: npm install
      
      - name: Run check README
        id: check
        run: echo "::set-output name=output::$(node index.js)"

      - name: debug 
        run: echo "${{ steps.check.outputs.output }}"

      - name: Commit changes
        if: steps.check.outputs.output == 'updated'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update status badge"

