name: Check Links
on:
  push:
    branches:
      - main 
jobs:
  check-links:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install packages
        run: npm install --global markdown-link-check
      - name: Update README
        run: |
          markdown-link-check -c .github/workflows/.markdownlinkcheck.json README.md > output.txt || true
          while read line; do
          if echo $line | grep -q "FAIL"; then
          link=$(echo $line | awk '{print $4}')
          sed -i "s|$link|❌ $link|g" README.md
          fi
          done < output.txt
      - name: Commit changes
        if: ${{ failure() }}
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update1 README.md"
          commit_options: "--no-verify --signoff"
